### ISSUE TITLE
linien-influxdb does not send the requested data after relocking

### ISSUE THREAD

**Issue by yasio90** [linien-org/linien-influxdb#18]
We observed that if one relocks a laser, some parameters (e.g. error signal std) is not sent to the database. 

I one clicks 'stop lock' in linien, linien-influxdb stops pushing some of the parameters to the database (we monitor error signal std and monitor mean, the latter is sent, but the former stops being sent after unlocking). After locking again the situation persists - only monitor mean is pushed to the database. I think that the desired behavior would be that upon locking again all the requested parameters are pushed to the database again.

**Comment by bleykauf** [comment]
Thank you for pointing that out. Could replicate it finally (no laser locking in the last month) and will look into it.

**Comment by bleykauf** [comment]
@yasio90 new version is up on PyPi

**Comment by yasio90** [comment]
@bleykauf I tested also on my side and it works very well. Great thanks!
